### ISSUE TITLE
Nada de binarios en el repo

### ISSUE THREAD

**Issue by JJ** [guillesiesta/Memoria_TFG_GuillermoMuriel#1]
El pdf debes subirlo en "release". Haz git tag para etiquetar el commit con los fuentes con los que generas el pdf

**Comment by JJ** [comment]
Aparte, está muy desactualizado...

**Comment by guillesiesta** [comment]
No entiendo bien a qué te refieres ni cuales serían los pasos a seguir. Agradecería un poco más profundidad.

**Comment by JJ** [comment]
Que borres el pdf y lo subas a una release
